### PR TITLE
fix(lean): Lean-10 LeanDojo repaired end-to-end — lean-dojo 2.2.0 + toolchain v4.11 pairing (Closes #2789)

### LINKED ISSUE #2789: fix(lean): re-execute Lean series notebooks — 3 CRITICAL (errors in every cell) + toolchain alignment + companion lake updates
## Problem

Many Lean series notebooks have stale or broken outputs on `main`. An audit of all 21 notebooks reveals **3 CRITICAL** (every cell erroring), **4 MINOR** issues, and significant toolchain version drift across companion lake projects.

### CRITICAL — 3 notebooks (every cell errors)

| # | Notebook | Kernel | Cells w/ error | `severity:error` | Root cause |
|---|----------|--------|---------------|-------------------|------------|
| 4 | `Lean-4-Quantifiers.ipynb` | lean4-wsl | 25/25 | 172 | REPL launched without prelude/imports — `Unknown identifier: Nat`, `Unknown constant: CoeSort, OfNat`, parser failures |
| 15 | `Lean-15-Kochen-Specker.ipynb` | python3 | 13/13 | 30 | Lean code contains French identifiers/punctuation incompatible with parser |
| 16 | `Lean-16-Conway-Free-Will-Theorem.ipynb` | python3 | 14/14 | 58 | Same as Lean-15 — `invalid 'import' command`, French identifiers (`temps`, `deux`, `en`, `l'argument`) |

### MINOR — 4 notebooks

| # | Notebook | Issue |
|---|----------|-------|
| 7 | `Lean-7-LLM-Integration.ipynb` | 1 unknown identifier (`'foo'` in demo cell) |
| 7b | `Lean-7b-Examples.ipynb` | 1 unknown constant (`OfNat`) + API connection retries |
| 9 | `Lean-9-SK-Multi-Agents.ipynb` | 3 subprocess errors (`No such command '.../Main.lean'`) |
| 10 | `Lean-10-LeanDojo.ipynb` | `[ERROR] Import echoue: No module named 'lean_dojo'` |

### CLEAN — 14 notebooks

Lean-1, Lean-2, Lean-3, Lean-5, Lean-6, Lean-8, Lean-11, Lean-11-TorchLean-Python, Lean-12, Lean-13, Lean-13b, Lean-14a, Lean-14b, Lean-14c.

## Toolchain Version Drift

| Lake project | Current toolchain | Status |
|---|---|---|
| `mathlib_examples/` | v4.27.0 | Behind — 2+ releases old |
| `sensitivity_lean/` | v4.30.0-rc2 | RC — not stable |
| `conway_lean/` | v4.30.0-2 (not pinned — wrong format) | Anomaly — mixed format |
| `grothendieck_lean/` | v4.30.0-rc2 | RC — not stable |
| `calibration_lean/` | v4.30.0-rc2 | RC — not stable |
| `stable_marriage/upstream/` | v4.25.0 | Oldest — 3+ releases behind |

Installed in WSL: v4.11.0 through v4.31.0-rc2.

### Phase 1 — Fix CRITICAL notebooks (priority)
1. **Lean-4**: Diagnose lean4-wsl REPL startup (missing prelude? wrong `LEAN_PATH`?); fix import/setup; re-execute
2. **Lean-15 + Lean-16**: Fix French identifiers/punctuation in Lean code cells; re-execute
3. For all 3: papermill re-execution + H.3 validation (`execution_count` sequential, 0 error, 0 banned pattern)

### Phase 2 — Toolchain alignment
1. Unify companion lake projects to current **stable** Lean (not RC)
2. Run `lake update mathlib` in each project to bump Mathlib dependency
3. Run `lake build` in each project to verify compilation post-update
4. Document the chosen stable version in a shared reference

### Phase 3 — Fix MINOR notebooks
1. Lean-7/7b: fix unknown identifier/constant, test API connectivity
2. Lean-9: fix subprocess invocation path
3. Lean-10: install `lean_dojo` dependency or document alternative

### Phase 4 — Re-execute all 21 notebooks
- Full papermill pass on the series to ensure consistent outputs
- H.3 validation (exec_count sequential, 0 error)
- Commit with outputs (C.2)

## Acceptance Criteria
- [ ] 0 notebook with `severity:error` in outputs
- [ ] All companion lake projects on same stable toolchain (not RC)
- [ ] `lake build` passes in all companion projects
- [ ] All 21 notebooks papermill-executed with sequential exec_count
- [ ] H.3 validation passes on all 21 notebooks
- [ ] README Lean updated with current state

## Context
- Lean execution requires WSL + lean4-wsl kernel (cf `.claude/rules/wsl-kernels.md`)
- Rule F: install missing kernels/envs, never bypass
- Rule H.3: no commit of unexecuted notebook
- Scripts: `scripts/notebook_tools/wsl_papermill.py` with `--kernel lean4-wsl`

See #1452 (Lean prover epic), #1453 (prover iterations), #2161 (3 exercises/notebook)

### PR DESCRIPTION
**Pull request by jsboige**
## Summary

Fixes the last MINOR notebook of the Lean series audit: `Lean-10-LeanDojo.ipynb` failed with `No module named 'lean_dojo'` and had non-sequential exec_counts. Per rule F (install/repair, never bypass): the full LeanDojo stack was repaired in WSL — ending with the discovery that **lean-dojo 4.20.0's interactive Dojo is structurally broken on the Lean toolchains it supports**, fixed by pinning lean-dojo 2.2.0 + repinning the demo repo to a v4.11.0 commit — then full papermill re-execution with real tracing AND a real interactive Dojo (tactics executed, proof finished).

Closes #2789

## Root cause (5 layers, peeled in order)

1. **`lean_dojo` missing from all 3 WSL Python envs.** The audit's "pip install lean-dojo" had been done Windows-side only; the notebook runs in WSL. Installed in `/usr/bin/python3`, `~/.lean4-venv`, and `~/coursia-wsl` (papermill venv — whose own sys.prefix `python3` kernelspec shadows the user-level one; this is the env papermill actually resolves).
2. **`~/.elan/bin` absent from the papermill kernel PATH**: `wsl_papermill.py` invoked WSL via `bash -c` (non-login), so lean_dojo tracing's internal `lake build` died with exit 127. Fixed by switching to `bash -lc` — benefits every WSL notebook that shells out to lake/lean.
3. **OOM-kill during tracing**: lean_dojo parallelizes tracing over `NUM_PROCS` = cpu_count (20) lean processes; on the 8 GB `.wslconfig` VM the kernel OOM-killer killed `lean` mid-trace (dmesg evidence). Capped via `os.environ.setdefault("NUM_PROCS", "4")` in the notebook config cell, *before* the import (read at import time, `lean_dojo/constants.py`).
4. **WSL process-lifetime kills**: (a) WSL stops the systemd user manager when the last wsl.exe session closes — fixed permanently with `loginctl enable-linger jesse`; (b) WSL terminates the whole distro once the last relay closes, so long tracing must keep its launching relay attached. This explains the silent mid-cell deaths with no error output.
5. **lean-dojo 4.20.0's interactive `Dojo` is structurally broken on Lean >= 4.19** — and 4.20.0 can only trace Lean >= 4.19. Two independent breakages, both verified by direct toolchain tests: (a) Lean >= 4.19 isolates stdin during elaboration, so the in-tactic REPL (`Lean4Repl`) reads empty input (tested: in-tactic `IO.getStdin.getLine` returns data on 4.11, empty on 4.19/4.20); (b) Lean >= 4.19 removed the `--memory` flag that lean-dojo passes to `lake env lean` → exit 1 (`DojoInitError`). Conversely 4.20.0's `ExtractData.lean` does not compile on Lean v4.11 (`getImports` signature changed `Syntax` → `TSyntax`), so it cannot trace old toolchains either — and `yangky11/lean4-example` jumps straight from v4.11.0 to v4.19.0 in its history: **no commit of the demo repo works with lean-dojo 4.20.0 end-to-end**. The working pair is **lean-dojo 2.2.0 + toolchain <= v4.11**. Validated standalone before the notebook run: trace OK, Dojo opens, `run_tac` returns `ProofFinished`.

## Changes

- `scripts/notebook_tools/wsl_papermill.py`: `bash -c` → `bash -lc` (+comment).
- `MyIA.AI.Notebooks/SymbolicAI/Lean/Lean-10-LeanDojo.ipynb`:
  - Repo pins moved `7761283d` (v4.20.0) → `4164749e` (v4.11.0) with a comment block documenting the LeanDojo↔toolchain pairing; install cell now prescribes `pip install --ignore-requires-python lean-dojo==2.2.0` (2.2.0 declares `requires_python = "<=3.12"`, which per PEP 440 wrongly excludes 3.12.1+; the code is 3.12-compatible).
  - API adaptation to the real `run_tac` contract: it returns a **union** `TacticState | ProofFinished | LeanError` (never `None`); the notebook's old None-based handling crashed with `AttributeError: 'LeanError' object has no attribute 'goals'`. Imports, both Dojo loops, the LLM pseudo-code cell and 3 markdown cells updated to isinstance-based handling; the two "Interpretation : ... Desactive" markdown cells rewritten for the now-active Dojo demo. `Dojo(thm, build_deps=...)` → `Dojo(thm)` (kwarg does not exist in 2.2.0).
  - Config cell gains the documented `NUM_PROCS` cap (layer 3); limitations table gains the "Dojo broken on Lean >= 4.19" row.
  - Re-executed end-to-end with outputs (C.2): real tracing of `lean4-example@4164749e`, real Dojo interaction (`ENABLE_DOJO_DEMO=True`, `ENABLE_AUTO_PROOF=True`).

## Rule D evidence (notebook PR)

1. **Papermill execution (WSL, kernel python3)**: `wsl_papermill.py execute Lean-10-LeanDojo.ipynb --timeout 3600` → `OK: 27/27 cells executed, 0 errors (13.7s)`. Fast run = cache hit on the pre-validated trace: tracing cell logs `[CACHE HIT]` + `Loading the traced repo from ~/.cache/lean_dojo/yangky11-lean4-example-4164749e.../` (6.5s). Dojo cell: `Buts initiaux: 1` → `'omega' [OK]` → `Buts restants: 0` → `[OK] Preuve terminee!`. Auto-proof cell: `Succes: True` (intro FAIL → intros OK → rfl/simp/trivial FAIL → omega OK).
2. **0 banned pattern**: `grep -nE "raise NotImplementedError|assert False|1/0"` → no match in executed cells (exercise stubs use print/pass).
3. **H.3 validation**: 27 code cells, `execution_count` = 1..27 strictly sequential, 0 null, 0 error outputs. Import cell output shows `LeanDojo version: 2.2.0`; 0 occurrences of `4.20.0` in any output; theorem extraction is real (2 user theorems `hello_world`/`foo` from `Lean4Example.lean`, not the demo fallback).
4. No `# Solution` / worked-example cell removed — source changes are the repin + API adaptation described above; all outputs regenerated by the run.

## Issue #2789 statuation

Posted as issue comment: phases 1/3 DONE (#2791, #2793, this PR; Lean-7/7b = stale audit), phase 2 (toolchain) re-routed to #2611 (junction discipline; the `conway_lean` "wrong format" claim is a false positive — actual pin is `v4.30.0-rc2`), phase 4 (blanket re-exec of 21 notebooks) replaced by scan-based verification per rule C.3.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by jsboige — COMMENTED** [review]
**[NanoClaw]**

## Review: Lean-10 LeanDojo E2E Repair (#2815)

### Verdict: LGTM -- solid fix with thorough root-cause documentation.

### What changed (2 files)

1. **`Lean-10-LeanDojo.ipynb`** (+725/-528): Full papermill re-execution with the LeanDojo stack repaired. Previously the notebook was in "demo mode" (every functional cell outputting `[MODE DEMO]` / `[SKIP]` because `lean_dojo` wasn't importable). Now all cells produce real outputs: tracing from cache (6.5s), theorem extraction (2 theorems from Lean4Example.lean), Dojo interactive proof (`intros` then `omega` closes `hello_world`), auto-proof runner, and LeanRunner integration.

2. **`scripts/notebook_tools/wsl_papermill.py`** (+3/-1): `bash -c` -> `bash -lc` so `~/.profile` is sourced, putting `~/.elan/bin` on PATH for any WSL notebook that shells out to `lake`/`lean`. Correct, well-commented, and benefits all WSL notebooks.

### Code changes (non-output)

- **`NUM_PROCS` cap** (config cell): `os.environ.setdefault("NUM_PROCS", "4")` before first import to prevent OOM-kill on 8 GB WSL VM. Correct placement (lean_dojo reads at import time).
- **lean-dojo 2.2.0 pin**: Detailed comments explaining why 4.20.0's interactive Dojo is structurally broken on Lean >= 4.19 (stdin isolation + `--memory` flag removed). `--ignore-requires-python` needed because 2.2.0's PEP 440 bound erroneously excludes Python 3.12.1+.
- **Commit repinned** to `4164749e` (lean-toolchain v4.11.0) for both `micro` and `small` configs. Consistent.
- **`build_deps=False`**: Added to trace calls to avoid OOM on full stdlib rebuild.
- **Theorem re-anchoring**: Three cells that open a Dojo now re-anchor `thm.repo.url` to the GitHub URL before `Dojo(thm)`, preventing cache-key mismatch and redundant re-tracing. Clean pattern.
- **`run_tac` API updated**: Switched from `None`-check to `isinstance` union (`TacticState` / `ProofFinished` / `LeanError`) matching lean-dojo 2.2.0 API. Applied consistently across all three Dojo cells (manual tactics, auto-proof, LLM function).
- **LeanRunner import**: Wrapped in try/except setting `RUNNER_AVAILABLE` flag. Better than crashing.
- **New compatibility warning cell**: Blockquote explaining the version pairing issue with issue reference #2789.

### Notebook output checks

- **execution_count**: No N/A, null, or QuantBook artifacts. One cell corrected from stale `1` to `27` with full execution metadata.
- **Timestamps**: All consistent `2026-06-11T13:02:xxZ` (single papermill run).
- **Outputs are real**: LeanDojo import produces `LeanDojo version: 2.2.0` (not fake); tracing shows cache hit with Ray progress bar; Dojo output shows actual Lean goal structures (`Goal(assumptions=[...], conclusion='a + b + c = a + c + b')`) and tactic results (`omega` closes the proof). No round/fake numbers.
- **Total execution time**: 12.9s (up from 2.3s demo), consistent with real tracing + Dojo interaction.
- **Pedagogical content**: All markdown interpretation cells updated from "demo mode" explanations to actual-result descriptions. Code examples in markdown updated to use `isinstance` API.

### Security

No secrets, API keys, or hardcoded credentials in diff. The only `token` hit is a removed line referencing `https://github.com/settings/tokens` in the old GitHub config cell output (safe, already deleted).

### Fixes #2789

Issue reported `[ERROR] Import echoue: No module named 'lean_dojo'`. The PR addresses this with 5-layer root-cause fix (missing WSL install, PATH issue, OOM cap, process lifetime, and version pairing). The notebook now runs end-to-end with real LeanDojo tracing and interactive proof.

**Comment by jsboige** [comment]
Conflits détectés — la base est ante-#2813/#2814. Peux-tu rebaser sur `origin/main` à jour ? Le contenu est validé (root cause 5 couches documentée, papermill OK, NanoClaw LGTM). J'ai aussi noté l'indentation du re-ancrage code à 8 espaces au lieu de 4 dans les cellules 39/42/51 (sous le `else:` à 4 espaces) — à corriger au passage si possible, même si les cellules Dojo sont bloquées upstream.

**Comment by jsboige** [comment]
Rebase fait (merge d'`origin/main` à jour, commit `20c2e2e2`) — PR de nouveau MERGEABLE.

**Résolution du conflit** : la version branche est conservée intégralement pour `Lean-10-LeanDojo.ipynb` (réparation complète lean-dojo 2.2.0 + repo@`4164749e`, exécutée 27/27 — elle supersède les patches partiels de #2814 qui gardaient le pin 4.20.0 avec cellules Dojo bloquées). `wsl_papermill.py` a mergé proprement.

**Indentation cellules 39/42/51** : vérifiée — le problème 8-espaces-sous-`else:` de #2814 n'existe pas dans cette version. Le re-ancrage y est restructuré en `if getattr(thm.repo, 'url', None) != repo.url:` à 4 espaces / corps à 8 (indentation standard), AST-validé 0 erreur sur les 27 cellules, et exécuté réellement. Rien à corriger, donc pas de re-exécution nécessaire (aucun changement de source depuis le commit exécuté `8001db75`).

**Review by jsboige — COMMENTED** [review]
**[Hermes] — COMMENT (self-review cap)**

**Checklist:**
1. ✅ Security: CLEAN — `GITHUB_ACCESS_TOKEN=***` is in a **removed** pedagogical markdown line (template placeholder), no new secrets introduced.
2. ✅ Notebook outputs: real papermill run 2026-06-11, 27/27 sequential execution_counts, real Dojo interaction (`omega [OK]`, `Proof terminée`, 944ms auto-proof). No stub outputs.
3. ✅ Root cause analysis: thorough 5-layer peel (missing env → PATH → OOM → WSL lifetime → lean-dojo/Lean incompatibility). The lean-dojo 2.2.0 + toolchain v4.11 pairing is well-documented with rationale.
4. ✅ NUM_PROCS cap before import — correct defensive pattern for resource-constrained WSL.
5. ✅ `bash -lc` fix in `wsl_papermill.py` — benefits all WSL notebooks.

**Note:** lean-dojo pinned to 2.2.0 with `--ignore-requires-python` — this is acceptable given the documented upstream PEP 440 bug. The version constraint is commented in the notebook for future maintainers.

No concerns. Well-documented repair PR.
